[global]
interface="wlan0"
download="10Mbps"
upload="10Mbps"
download_minimum= "100Kbps"
upload_minimum= "10Kbps"
download_priority= 0
upload_priority= 0

[[process]]
rule_name="Firefox"
download="2Mbps"
upload="10Mbps"
download_minimum= "100Kbps"
upload_minimum= "10Kbps" 
download_priority= 1
upload_priority= 1
match_exe="firefox"

[[process]]
rule_name="ssh"
download="5Mbps"
upload="10Mbps"
download_minimum= "100Kbps"
upload_minimum= "10Kbps"
download_priority= 1
upload_priority= 1
match_exe="sshd"
